### ISSUE TITLE
系统验证码识别模块无法正常工作

### ISSUE THREAD

**Issue by zhenxuanfeng** [chaoxue-sysu/sysu_books#1]
实测程序在get_captcha()函数处会无限循环

**Comment by chaoxue-sysu** [comment]
因为近期把  `recognize_captcha.py`中 `get_AT()` 方法里我申请的百度智能云AK和SK去掉了，所以导致验证码一直识别不成功，造成不断循环。
就是这一句：
```  python
# client id 为百度智能云官网获取的AK， client secret 为官网获取的SK
    AK='client id'
    SK='clien secret'
```
你可以自己申请，填上自己的API Key、Secret Key（即AK、SK）就可以了。（申请参考链接：http://ai.baidu.com/forum/topic/show/867951 ）

**Comment by chaoxue-sysu** [comment]
> 实测程序在get_captcha()函数处会无限循环

因为近期把  `recognize_captcha.py`中 `get_AT()` 方法里我申请的百度智能云AK和SK去掉了，所以导致验证码一直识别不成功，造成不断循环。
就是这一句：
```  python
# client id 为百度智能云官网获取的AK， client secret 为官网获取的SK
    AK='client id'
    SK='clien secret'
```
你可以自己申请，填上自己的API Key、Secret Key（即AK、SK）就可以了。（申请参考链接：http://ai.baidu.com/forum/topic/show/867951 ）

**Comment by zhenxuanfeng** [comment]
已解决，建议在代码或readme中加入说明
